// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMOhCcrZOpfTmHQNuuPChp0qiLJiu6eZg',
    appId: '1:254902397184:web:43c6100121ba97ac89ebe5',
    messagingSenderId: '254902397184',
    projectId: 'cagacash',
    authDomain: 'cagacash.firebaseapp.com',
    storageBucket: 'cagacash.firebasestorage.app',
    measurementId: 'G-PW47NBRXK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7w2Tvl9s9fDcqpAv4RAsgsV78TkZgw2U',
    appId: '1:254902397184:android:4f2f85cb9f2bb45e89ebe5',
    messagingSenderId: '254902397184',
    projectId: 'cagacash',
    storageBucket: 'cagacash.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2i_DTvHEDP9QQBw3B51WI5dFIWpFvb8o',
    appId: '1:254902397184:ios:1643da533a06881889ebe5',
    messagingSenderId: '254902397184',
    projectId: 'cagacash',
    storageBucket: 'cagacash.firebasestorage.app',
    iosBundleId: 'com.luiz.cagaCash',
  );

}